;;; miniflux-test.el --- Tests for miniflux.el -*- lexical-binding: t; -*-

(require 'ert)
(require 'miniflux)

(ert-deftest miniflux-api-url-adds-v1 ()
  (let ((miniflux-server "https://example.com"))
    (should (equal (miniflux--api-url "/entries")
                   "https://example.com/v1/entries"))))

(ert-deftest miniflux-api-url-keeps-existing-v1 ()
  (let ((miniflux-server "https://example.com/v1/"))
    (should (equal (miniflux--api-url "/entries")
                   "https://example.com/v1/entries"))))

(ert-deftest miniflux-auth-headers-prefers-token ()
  (let ((miniflux-token "token")
        (miniflux-username "user")
        (miniflux-password "pass"))
    (should (equal (miniflux--auth-headers)
                   '(("X-Auth-Token" . "token"))))))

(ert-deftest miniflux-auth-headers-uses-basic-auth ()
  (let ((miniflux-token "")
        (miniflux-username "user")
        (miniflux-password "pass"))
    (should (equal (miniflux--auth-headers)
                   `(("Authorization" . ,(concat "Basic "
                                                  (base64-encode-string "user:pass" t))))))))

(ert-deftest miniflux-auth-headers-uses-auth-source-token ()
  (let ((miniflux-server "https://reader.example.com")
        (miniflux-token "")
        (miniflux-username "")
        (miniflux-password ""))
    (cl-letf (((symbol-function 'auth-source-search)
               (lambda (&rest _args)
                 (list (list :user "token"
                             :secret (lambda () "secret-token"))))))
      (should (equal (miniflux--auth-headers)
                     '(("X-Auth-Token" . "secret-token")))))))

(ert-deftest miniflux-auth-headers-uses-auth-source-basic-auth ()
  (let ((miniflux-server "https://reader.example.com")
        (miniflux-token "")
        (miniflux-username "")
        (miniflux-password ""))
    (cl-letf (((symbol-function 'auth-source-search)
               (lambda (&rest _args)
                 (list (list :user "alice" :secret "s3cret")))))
      (should (equal (miniflux--auth-headers)
                     `(("Authorization" . ,(concat "Basic "
                                                    (base64-encode-string "alice:s3cret" t)))))))))

(ert-deftest miniflux-check-auth-accepts-auth-source ()
  (let ((miniflux-server "https://reader.example.com")
        (miniflux-token "")
        (miniflux-username "")
        (miniflux-password ""))
    (cl-letf (((symbol-function 'auth-source-search)
               (lambda (&rest _args)
                 (list (list :user "token" :secret "secret-token")))))
      (should (miniflux--check-auth)))))

(ert-deftest miniflux-request-url-encodes-params ()
  (let ((miniflux-server "https://example.com"))
    (should (equal (miniflux--request-url "/entries" '(("status" . "unread")
                                                        ("search" . "foo bar")))
                   "https://example.com/v1/entries?status=unread&search=foo%20bar"))))

(ert-deftest miniflux-json-error-message-extracts-message ()
  (should (equal (miniflux--json-error-message "{\"error_message\":\"bad token\"}")
                 "bad token")))

(ert-deftest miniflux-parse-response-returns-nil-for-http-error ()
  (with-temp-buffer
    (insert "HTTP/1.1 401 Unauthorized\r\n\r\n{\"error_message\":\"bad token\"}")
    (goto-char (point-min))
    (should-not (miniflux--parse-response))))

(ert-deftest miniflux-get-counters-parses-numeric-feed-ids ()
  (cl-letf (((symbol-function 'miniflux--request)
             (lambda (_method _path)
               (list (cons 'unreads
                           (list (cons (intern "42") 5)
                                 (cons (intern "invalid") 9)
                                 (cons (intern "7") 2)))))))
    (should (equal (miniflux--get-counters)
                   '((42 . 5) (7 . 2))))))

(ert-deftest miniflux-slugify-trims-dashes ()
  (should (equal (miniflux--slugify "  Tech & News!  ") "tech-news")))

(ert-deftest miniflux-entry-category-tag-normalizes-title ()
  (let ((entry '((feed . ((category . ((title . "Tech News")))))))
        (miniflux-category-tag-prefix "miniflux-category-"))
    (should (eq (miniflux--entry-category-tag entry)
                'miniflux-category-tech-news))))

(ert-deftest miniflux-category-tag-p-ignores-empty-prefix ()
  (let ((miniflux-category-tag-prefix ""))
    (should-not (miniflux--category-tag-p 'unread))
    (should-not (miniflux--category-tag-p 'blog))))

(ert-deftest miniflux-entry-meta-is-plist ()
  (let* ((entry '((id . 7806)
                  (author . "Mitchell")
                  (feed . ((id . 454)
                           (site_url . "https://mitchellh.com")
                           (feed_url . "https://mitchellh.com/feed.xml")
                           (category . ((id . 5) (title . "Blogs")))))))
         (meta (miniflux--entry-meta entry "Mitchell")))
    (should (plistp meta))
    (should (equal (plist-get meta :miniflux-id) 7806))
    (should (equal (plist-get meta :miniflux-feed-id) 454))
    (should (equal (plist-get meta :site-url) "https://mitchellh.com"))
    (should (equal (plist-get meta :feed-url) "https://mitchellh.com/feed.xml"))
    (should (equal (plist-get meta :miniflux-category-title) "Blogs"))))

(ert-deftest miniflux-entry-to-elfeed-has-plist-meta ()
  (let* ((api-entry '((id . 7806)
                      (title . "Title")
                      (url . "https://example.com/post")
                      (status . "unread")
                      (starred . t)
                      (feed . ((id . 454)
                               (title . "Feed")
                               (site_url . "https://mitchellh.com")
                               (feed_url . "https://mitchellh.com/feed.xml")
                               (category . ((id . 5) (title . "Blogs")))))))
         (entry (miniflux--entry-to-elfeed api-entry "miniflux://454")))
    (should (plistp (elfeed-entry-meta entry)))
    (should (equal (plist-get (elfeed-entry-meta entry) :miniflux-id) 7806))
    (should (equal (plist-get (elfeed-entry-meta entry) :site-url)
                   "https://mitchellh.com"))))

(ert-deftest miniflux-plist-merge-overrides-new-values ()
  (should (equal (miniflux--plist-merge '(:miniflux-id 2 :site-url "new")
                                        '(:miniflux-id 1 :user-note "keep"))
                 '(:miniflux-id 2 :user-note "keep" :site-url "new"))))

(ert-deftest miniflux-fetch-entry-pages-async-fetches-all-pages ()
  (let ((miniflux-sync-limit 2)
        (miniflux-sync-pages-limit 5)
        (requests nil)
        result)
    (cl-letf (((symbol-function 'miniflux--request-async)
               (lambda (_method _path callback _data params)
                 (push params requests)
                 (funcall callback
                          (if (= (string-to-number (assoc-default "offset" params)) 0)
                              '((total . 3)
                                (entries . [((id . 1)) ((id . 2))]))
                            '((total . 3)
                              (entries . [((id . 3))])))))))
      (miniflux--fetch-entry-pages-async (list :status "unread") t
                                         (lambda (value)
                                           (setq result value)))
      (should (= (length (nth 0 result)) 3))
      (should (nth 1 result))
      (should (= (nth 2 result) 3))
      (should (nth 3 result))
      (should (= (length requests) 2)))))

(ert-deftest miniflux-fetch-entry-pages-async-stops-after-first-when-not-full ()
  (let ((miniflux-sync-limit 2)
        (miniflux-sync-pages-limit 5)
        (requests 0)
        result)
    (cl-letf (((symbol-function 'miniflux--request-async)
               (lambda (_method _path callback _data _params)
                 (setq requests (1+ requests))
                 (funcall callback '((total . 3)
                                     (entries . [((id . 1)) ((id . 2))]))))))
      (miniflux--fetch-entry-pages-async nil nil
                                         (lambda (value)
                                           (setq result value)))
      (should (= (length (nth 0 result)) 2))
      (should-not (nth 1 result))
      (should (= requests 1)))))

(ert-deftest miniflux-fetch-entry-pages-async-uses-async-limit ()
  (let ((miniflux-sync-limit 1000)
        (miniflux-sync-pages-limit 1)
        used-limit)
    (cl-letf (((symbol-function 'miniflux--request-async)
               (lambda (_method _path callback _data params)
                 (setq used-limit (assoc-default "limit" params))
                 (funcall callback '((total . 0) (entries . []))))))
      (miniflux--fetch-entry-pages-async nil nil #'ignore)
      (should (equal used-limit "100")))))

(ert-deftest miniflux-reconcile-all-stars-uses-custom-star-tag ()
  (let* ((miniflux-sync-star-tag 'favorite)
         (elfeed-db-entries (make-hash-table :test 'equal))
         (api-starred-ids (make-hash-table :test 'equal))
         (id (cons 'miniflux "1"))
         (entry (elfeed-entry--create :id id :title "t" :tags '(unread))))
    (puthash id entry elfeed-db-entries)
    (puthash id t api-starred-ids)
    (should (= (miniflux--reconcile-all-stars api-starred-ids t) 1))
    (should (memq 'favorite (elfeed-entry-tags entry)))
    (should-not (memq 'star (elfeed-entry-tags entry)))))

(ert-deftest miniflux-reconcile-stars-incomplete-batch-does-not-remove ()
  (let* ((elfeed-db-entries (make-hash-table :test 'equal))
         (api-starred-ids (make-hash-table :test 'equal))
         (id (cons 'miniflux "1"))
         (entry (elfeed-entry--create :id id :title "t" :tags '(star))))
    (puthash id entry elfeed-db-entries)
    (should (= (miniflux--reconcile-all-stars api-starred-ids nil) 0))
    (should (memq 'star (elfeed-entry-tags entry)))))

(ert-deftest miniflux-reconcile-stars-complete-batch-removes-missing ()
  (let* ((elfeed-db-entries (make-hash-table :test 'equal))
         (api-starred-ids (make-hash-table :test 'equal))
         (id (cons 'miniflux "1"))
         (entry (elfeed-entry--create :id id :title "t" :tags '(star))))
    (puthash id entry elfeed-db-entries)
    (should (= (miniflux--reconcile-all-stars api-starred-ids t) 1))
    (should-not (memq 'star (elfeed-entry-tags entry)))))

(ert-deftest miniflux-reconcile-stars-ignores-non-miniflux-entries ()
  (let* ((elfeed-db-entries (make-hash-table :test 'equal))
         (api-starred-ids (make-hash-table :test 'equal))
         (id "https://example.com/post")
         (entry (elfeed-entry--create :id id :title "t" :tags '(star))))
    (puthash id entry elfeed-db-entries)
    (should (= (miniflux--reconcile-all-stars api-starred-ids t) 0))
    (should (memq 'star (elfeed-entry-tags entry)))))

(ert-deftest miniflux-reconcile-unread-incomplete-batch-does-not-remove ()
  (let* ((elfeed-db-entries (make-hash-table :test 'equal))
         (api-unread-ids (make-hash-table :test 'equal))
         (id (cons 'miniflux "1"))
         (entry (elfeed-entry--create :id id :title "t" :tags '(unread))))
    (puthash id entry elfeed-db-entries)
    (should (= (miniflux--reconcile-all-unread api-unread-ids nil) 0))
    (should (memq 'unread (elfeed-entry-tags entry)))))

(ert-deftest miniflux-reconcile-unread-complete-batch-removes-missing ()
  (let* ((elfeed-db-entries (make-hash-table :test 'equal))
         (api-unread-ids (make-hash-table :test 'equal))
         (id (cons 'miniflux "1"))
         (entry (elfeed-entry--create :id id :title "t" :tags '(unread))))
    (puthash id entry elfeed-db-entries)
    (should (= (miniflux--reconcile-all-unread api-unread-ids t) 1))
    (should-not (memq 'unread (elfeed-entry-tags entry)))))

(ert-deftest miniflux-reconcile-entry-tags-preserves-user-tags ()
  (let* ((miniflux-category-tag-prefix "miniflux-category-")
         (elfeed-db-entries (make-hash-table :test 'equal))
         (api-table (make-hash-table :test 'equal))
         (id (cons 'miniflux "1"))
         (entry (elfeed-entry--create :id id
                                      :title "multi\nline"
                                      :tags '(unread favorite custom))))
    (puthash id entry elfeed-db-entries)
    (puthash id '((id . 1)
                  (author . "Ada")
                  (feed . ((id . 2)
                           (category . ((id . 3) (title . "Tech News")))))) api-table)
    (miniflux--reconcile-entry-tags api-table)
    (should (equal (elfeed-entry-title entry) "multi line"))
    (should (memq 'unread (elfeed-entry-tags entry)))
    (should (memq 'favorite (elfeed-entry-tags entry)))
    (should (memq 'custom (elfeed-entry-tags entry)))
    (should (memq 'miniflux-category-tech-news (elfeed-entry-tags entry)))
    (should (equal (plist-get (elfeed-entry-meta entry) :miniflux-category-title)
                   "Tech News"))))

(ert-deftest miniflux-reconcile-entry-tags-removes-stale-category-tags ()
  (let* ((miniflux-category-tag-prefix "miniflux-category-")
         (elfeed-db-entries (make-hash-table :test 'equal))
         (api-table (make-hash-table :test 'equal))
         (id (cons 'miniflux "1"))
         (entry (elfeed-entry--create :id id
                                      :title "t"
                                      :tags '(miniflux-category-old custom))))
    (puthash id entry elfeed-db-entries)
    (puthash id '((feed . ((category . ((title . "New")))))) api-table)
    (miniflux--reconcile-entry-tags api-table)
    (should-not (memq 'miniflux-category-old (elfeed-entry-tags entry)))
    (should (memq 'custom (elfeed-entry-tags entry)))
    (should (memq 'miniflux-category-new (elfeed-entry-tags entry)))))

(ert-deftest miniflux-reconcile-entry-tags-preserves-unread-with-empty-prefix ()
  (let* ((miniflux-category-tag-prefix "")
         (elfeed-db-entries (make-hash-table :test 'equal))
         (api-table (make-hash-table :test 'equal))
         (id (cons 'miniflux "1"))
         (entry (elfeed-entry--create :id id
                                      :title "t"
                                      :tags '(unread blog))))
    (puthash id entry elfeed-db-entries)
    (puthash id '((feed . ((category . ((title . "Blog")))))) api-table)
    (miniflux--reconcile-entry-tags api-table)
    (should (memq 'unread (elfeed-entry-tags entry)))
    (should (memq 'blog (elfeed-entry-tags entry)))))

(ert-deftest miniflux-push-entry-state-toggles-star-only-when-needed ()
  (let* ((entry (elfeed-entry--create :id (cons 'miniflux "7")
                                      :title "t"
                                      :tags '(unread star)))
         (status-calls nil)
         (toggle-calls 0))
    (cl-letf (((symbol-function 'miniflux-update-entry-status)
               (lambda (ids status)
                 (push (list ids status) status-calls)
                 t))
              ((symbol-function 'miniflux-get-entry)
               (lambda (_id) '((starred . nil))))
              ((symbol-function 'miniflux-toggle-entry-bookmark)
               (lambda (_id)
                 (setq toggle-calls (1+ toggle-calls))
                 t)))
      (should (miniflux--push-entry-state entry))
      (should (equal status-calls '(((7) "unread"))))
      (should (= toggle-calls 1)))))

(ert-deftest miniflux-push-entry-state-skips-star-toggle-when-matching ()
  (let* ((entry (elfeed-entry--create :id (cons 'miniflux "7")
                                      :title "t"
                                      :tags '(star)))
         (toggle-calls 0))
    (cl-letf (((symbol-function 'miniflux-update-entry-status)
               (lambda (_ids _status) t))
              ((symbol-function 'miniflux-get-entry)
               (lambda (_id) '((starred . t))))
              ((symbol-function 'miniflux-toggle-entry-bookmark)
               (lambda (_id)
                 (setq toggle-calls (1+ toggle-calls))
                 t)))
      (should (miniflux--push-entry-state entry))
      (should (= toggle-calls 0)))))

(ert-deftest miniflux-push-entry-state-marks-read-from-local-tags ()
  (let* ((entry (elfeed-entry--create :id (cons 'miniflux "7")
                                      :title "t"
                                      :tags nil))
         (status-calls nil))
    (cl-letf (((symbol-function 'miniflux-update-entry-status)
               (lambda (ids status)
                 (push (list ids status) status-calls)
                 t))
              ((symbol-function 'miniflux-get-entry)
               (lambda (_id) '((starred . nil)))))
      (should (miniflux--push-entry-state entry))
      (should (equal status-calls '(((7) "read")))))))

;;; miniflux-test.el ends here
